BEGIN;

-- Xóa dữ liệu cũ nếu có để tránh trùng lặp khi chạy lại
DELETE FROM quest_steps WHERE quest_id IN ('33333333-3333-3333-3333-333333333334', '33333333-3333-3333-3333-333333333335');
DELETE FROM quests WHERE id IN ('33333333-3333-3333-3333-333333333334', '33333333-3333-3333-3333-333333333335');

-- 1. CHIẾN DỊCH 2: MẬT MÃ SA BÀN TÁC CHIẾN (Anh Ba Chiến Sĩ)
INSERT INTO quests (id, location_id, title, description, story, points_reward, required_order, step_discovery_keys, completion_trigger, steps_total, cover_image) VALUES
    ('33333333-3333-3333-3333-333333333334', '11111111-1111-1111-1111-111111111111', 'Mật mã Sa bàn Tác chiến', 'Tìm hiểu cấu trúc 3 tầng ngầm và nghệ thuật du kích bẫy chông qua sa bàn quân sự.', 'Tại Củ Chi, vũ khí thô sơ đã chiến thắng khí tài hiện đại. Hệ thống 3 tầng ngầm với bẫy chông kẹp nách và chiến thuật đánh du kích đã biến Củ Chi thành "Đất Thép thành đồng".', 150, 2, 'dialogue:anh-ba,tour:sa-ban,era:1968', 'discovery', 3, '/media/heritage/dia-dao-cu-chi/cover.jpeg');

INSERT INTO quest_steps (id, quest_id, step_order, unlock_key, title, objective, description, hint, action_type, action_label, xp_partial, chat_prompt, portal_era, preview_image) VALUES
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333334', 1, 'dialogue:anh-ba', 'Chương 1 · Gặp Anh Ba Chiến Sĩ', 'Lấy thông tin tình báo về cấu trúc địa đạo 3 tầng.', 'Hỏi Anh Ba về cách quân dân ta đào 3 tầng ngầm sâu dưới lòng đất.', 'Hãy nhấn Gặp Anh Ba và gửi câu hỏi đã được chuẩn bị sẵn.', 'dialogue', 'Gặp Anh Ba', 30, 'Anh Ba hãy phân tích cấu trúc địa đạo 3 tầng ngầm Củ Chi?', NULL, '/media/characters/nam-du-kich.png'),
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333334', 2, 'tour:sa-ban', 'Chương 2 · Khảo sát Bẫy Chông', 'Vào tour 360° tìm hiểu mô hình hầm chông tự tạo.', 'Những chiếc bẫy tre thô sơ nhưng là nỗi khiếp sợ của quân thù.', 'Trong tour 360°, tìm điểm nóng "Khu vực Bẫy Chông".', 'tour', 'Vào Tour 360°', 50, NULL, NULL, '/media/heritage/dia-dao-cu-chi/cover.jpeg'),
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333334', 3, 'era:1968', 'Chương 3 · Phục kích Xe Tăng', 'Mở Time Portal xem cảnh phục kích xe tăng M41.', 'Tái hiện khoảnh khắc quân ta dùng chiến thuật du kích phá hủy xe tăng.', 'Mở Portal chọn mốc thời gian 1968.', 'portal', 'Mở Time Portal', 70, NULL, 1968, '/media/heritage/dia-dao-cu-chi/cover.jpeg');


-- 2. CHIẾN DỊCH 3: ÁNH SÁNG ĐÈN MÙ U (Chị Năm Du Kích)
INSERT INTO quests (id, location_id, title, description, story, points_reward, required_order, step_discovery_keys, completion_trigger, steps_total, cover_image) VALUES
    ('33333333-3333-3333-3333-333333333335', '11111111-1111-1111-1111-111111111111', 'Ánh sáng Đèn Mù U', 'Giải mã cuộc sống sinh hoạt, y tế và giáo dục dưới lòng đất của quân dân Củ Chi.', 'Dưới những lớp đất tối tăm, cuộc sống vẫn nảy mầm. Ánh sáng le lói từ chiếc đèn dầu mù u đã soi sáng những lớp học bình dân và trạm xá dã chiến.', 120, 3, 'dialogue:chi-nam,tour:tram-xa,era:1968', 'discovery', 3, '/media/heritage/dia-dao-cu-chi/cover.jpeg');

INSERT INTO quest_steps (id, quest_id, step_order, unlock_key, title, objective, description, hint, action_type, action_label, xp_partial, chat_prompt, portal_era, preview_image) VALUES
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333335', 1, 'dialogue:chi-nam', 'Chương 1 · Gặp Chị Năm Du Kích', 'Lắng nghe Chị Năm kể chuyện đời sống hầm ngầm.', 'Hỏi Chị Năm về cách người dân sinh hoạt, nấu ăn dưới địa đạo.', 'Nhấn Gặp Chị Năm và gửi câu hỏi gợi ý.', 'dialogue', 'Gặp Chị Năm', 30, 'Chị Năm ơi, cuộc sống sinh hoạt dưới hầm ngầm thế nào?', NULL, '/media/characters/nu-du-kich.png'),
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333335', 2, 'tour:tram-xa', 'Chương 2 · Trạm xá Dã chiến', 'Tìm kiếm trạm y tế dưới lòng đất trong Tour 360°.', 'Nơi các bác sĩ quân y cứu chữa thương binh trong điều kiện thiếu thốn.', 'Khám phá khu vực Trạm xá trong sa bàn 360°.', 'tour', 'Vào Tour 360°', 40, NULL, NULL, '/media/heritage/dia-dao-cu-chi/cover.jpeg'),
                                                                                                                                                                                       (gen_random_uuid(), '33333333-3333-3333-3333-333333333335', 3, 'era:1968', 'Chương 3 · Lớp học bình dân', 'Mở Time Portal chứng kiến lớp học dưới ánh đèn mù u.', 'Sự kiên cường của những đứa trẻ học chữ dưới làn bom đạn.', 'Mở Portal mốc 1968 tại khu vực Lớp học.', 'portal', 'Mở Time Portal', 50, NULL, 1968, '/media/heritage/dia-dao-cu-chi/cover.jpeg');

COMMIT;