<#
.SYNOPSIS
  B5 RAG ingest STUB: turns approved markdown (BE/src/main/resources/data/rag-approved/*.md) into SQL for
  rag_sources / rag_chunks (+ optional Gemini embeddings).

.DESCRIPTION
  Each .md file = one rag_sources row. Front matter (between --- lines):
    title, license, verified_by, verified_at (yyyy-MM-dd), era, station_code (empty = global), status
  Only files with status: approved AND verified_by AND verified_at are ingested; others are skipped.
  Chunks = one per "## " section (text before the first "## " is its own chunk).

  Default (dry run): parse + print a summary, and write the SQL WITHOUT embeddings (embedding stays NULL, so the
  chunks are not searchable yet).
  -Embed: call Gemini embedContent (needs $env:GEMINI_API_KEY) and write vector(768) literals into the SQL.

  Re-running is idempotent per source title: the script DELETEs the source with the same title first
  (rag_chunks cascade), which also replaces the placeholder rows seeded by V25__pgvector_rag.sql.

  The script never touches the database itself. Apply the generated file with psql, e.g.:
    psql "$env:DATABASE_URL" -v ON_ERROR_STOP=1 -f rag-ingest.generated.sql

.EXAMPLE
  ./rag-ingest-approved.ps1                       # dry run, SQL without embeddings
  $env:GEMINI_API_KEY = '...'; ./rag-ingest-approved.ps1 -Embed
#>
[CmdletBinding()]
param(
    [string]$Dir,
    [string]$OutSql,
    [switch]$Embed,
    [string]$Model = $(if ($env:RAG_EMBEDDING_MODEL) { $env:RAG_EMBEDDING_MODEL } else { 'gemini-embedding-001' }),
    [int]$Dimensions = 768
)

$ErrorActionPreference = 'Stop'
$root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $Dir) { $Dir = Join-Path $root '..\src\main\resources\data\rag-approved' }
if (-not $OutSql) { $OutSql = Join-Path $root 'rag-ingest.generated.sql' }

function ConvertTo-SqlString([string]$s) {
    if ($null -eq $s -or $s -eq '') { return 'NULL' }
    return "'" + $s.Replace("'", "''") + "'"
}

function Read-ApprovedDoc([string]$path) {
    $raw = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    $m = [regex]::Match($raw, '(?s)\A---\s*\r?\n(.*?)\r?\n---\s*\r?\n(.*)\z')
    if (-not $m.Success) { return $null }
    $meta = @{}
    foreach ($line in ($m.Groups[1].Value -split '\r?\n')) {
        $kv = [regex]::Match($line, '^\s*([A-Za-z_]+)\s*:\s*(.*?)\s*$')
        if ($kv.Success) { $meta[$kv.Groups[1].Value] = $kv.Groups[2].Value }
    }
    $chunks = New-Object System.Collections.Generic.List[string]
    $parts = [regex]::Split($m.Groups[2].Value, '(?m)^##\s+')
    for ($i = 0; $i -lt $parts.Count; $i++) {
        $text = $parts[$i].Trim()
        if ($text -eq '') { continue }
        if ($i -gt 0) {
            # "Heading\n\nBody" -> "Heading: Body"
            $split = $text -split '\r?\n', 2
            $body = if ($split.Count -gt 1) { ($split[1].Trim() -replace '\s*\r?\n\s*', ' ') } else { '' }
            $text = if ($body) { "$($split[0].Trim()): $body" } else { $split[0].Trim() }
        }
        $chunks.Add($text)
    }
    return [pscustomobject]@{ Meta = $meta; Chunks = $chunks; File = (Split-Path $path -Leaf) }
}

function Get-GeminiEmbedding([string]$text) {
    if (-not $env:GEMINI_API_KEY) { throw 'GEMINI_API_KEY is not set (required for -Embed).' }
    $body = @{
        model                = "models/$Model"
        content              = @{ parts = @(@{ text = $text }) }
        taskType             = 'RETRIEVAL_DOCUMENT'
        outputDimensionality = $Dimensions
    } | ConvertTo-Json -Depth 6
    $uri = "https://generativelanguage.googleapis.com/v1beta/models/${Model}:embedContent"
    $res = Invoke-RestMethod -Method Post -Uri $uri -ContentType 'application/json; charset=utf-8' `
        -Headers @{ 'x-goog-api-key' = $env:GEMINI_API_KEY } -Body ([Text.Encoding]::UTF8.GetBytes($body))
    $values = $res.embedding.values
    if ($values.Count -ne $Dimensions) { throw "Embedding has $($values.Count) dims, expected $Dimensions." }
    return '[' + (($values | ForEach-Object { ([double]$_).ToString('0.0000000', [Globalization.CultureInfo]::InvariantCulture) }) -join ',') + ']'
}

if (-not (Test-Path -LiteralPath $Dir)) { throw "Directory not found: $Dir" }
$files = Get-ChildItem -LiteralPath $Dir -Filter '*.md' -File | Sort-Object Name
if ($files.Count -eq 0) { Write-Warning "No .md files in $Dir"; return }

$sql = New-Object System.Text.StringBuilder
[void]$sql.AppendLine('-- Generated by rag-ingest-approved.ps1 - do not edit by hand.')
[void]$sql.AppendLine('BEGIN;')
$sources = 0; $chunkCount = 0

foreach ($f in $files) {
    $doc = Read-ApprovedDoc $f.FullName
    if ($null -eq $doc) { Write-Warning "SKIP $($f.Name): no front matter"; continue }
    $m = $doc.Meta
    if ($m['status'] -ne 'approved' -or -not $m['verified_by'] -or -not $m['verified_at'] -or -not $m['title']) {
        Write-Warning "SKIP $($f.Name): needs title + status: approved + verified_by + verified_at"
        continue
    }
    $sourceId = [guid]::NewGuid().ToString()
    $station = $m['station_code']
    Write-Host ("{0}: '{1}' station={2} chunks={3}" -f $f.Name, $m['title'], $(if ($station) { $station } else { '(global)' }), $doc.Chunks.Count)

    [void]$sql.AppendLine("DELETE FROM rag_sources WHERE title = $(ConvertTo-SqlString $m['title']);")
    [void]$sql.AppendLine("INSERT INTO rag_sources (id, title, license, verified_by, verified_at, era, station_code) VALUES ('$sourceId', $(ConvertTo-SqlString $m['title']), $(ConvertTo-SqlString $m['license']), $(ConvertTo-SqlString $m['verified_by']), $(ConvertTo-SqlString $m['verified_at']), $(ConvertTo-SqlString $m['era']), $(ConvertTo-SqlString $station));")
    $sources++

    for ($i = 0; $i -lt $doc.Chunks.Count; $i++) {
        $embedding = 'NULL'
        if ($Embed) {
            $embedding = "CAST('" + (Get-GeminiEmbedding $doc.Chunks[$i]) + "' AS vector)"
            Start-Sleep -Milliseconds 300   # stay under free-tier rate limits
        }
        [void]$sql.AppendLine("INSERT INTO rag_chunks (id, source_id, station_code, era, content, embedding, chunk_index) VALUES ('$([guid]::NewGuid())', '$sourceId', $(ConvertTo-SqlString $station), $(ConvertTo-SqlString $m['era']), $(ConvertTo-SqlString $doc.Chunks[$i]), $embedding, $i);")
        $chunkCount++
    }
}

[void]$sql.AppendLine('COMMIT;')
[IO.File]::WriteAllText($OutSql, $sql.ToString(), (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote $OutSql ($sources sources, $chunkCount chunks, embeddings: $([bool]$Embed))"
if (-not $Embed) { Write-Host 'Dry run: embeddings are NULL. Re-run with -Embed (needs GEMINI_API_KEY) to make chunks searchable.' }
Write-Host 'Apply with: psql "$env:DATABASE_URL" -v ON_ERROR_STOP=1 -f rag-ingest.generated.sql'
